project:
  type: book

book:
  title: "Chasing Python"
  subtitle: "Step into and run with Python for Data Science"
  description: "This book teaches Python programming fundamentals and data analytic stack to help you stepping into and runing with Python for data science. Python is an excellent programming language for data science and machine learning due to its simplicity, versatility, and the wealth of libraries available in its data analytic stack, including NumPy, Pandas, Matplotlib and Seaborn."
  author: "Enayetur Raheem"
  date:  "2023/07/24"
  cover-image: images/pybook-cover.png

  chapters:
    - index.qmd
    - outline.qmd

    - part: python.qmd
      chapters:
        - tba.qmd
    - part: numpy.qmd
      chapters:
        - tba.qmd
    - part: pandas.qmd
      chapters: 
        - tba.qmd
    - part: viz.qmd
      chapters:
        - tba.qmd
    - part: sklearn.qmd
      chapters:
        - tba.qmd
    - references.qmd

highlight-style: pygments

format:
  html:
    toc: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

bibliography: references.bib


